### ISSUE TITLE
How to send the query to a GraphQL server?

### ISSUE THREAD

**Issue by unuigbee** [WeltN24/GraphQLicious#14]
I'm trying to post a query using AFNetworking to my GraphQL server but i'm wondering how I would go about sending a query to a GraphQL server if it expects a JSON based request like this 
`{
query: "feed(type: BY_VOTES) {
               title 
            }    
            "
}` 

Since your library creates a query string like this: 
`query {
    feed(type: BY_VOTES) {
        title
   }
}` 

Is there someway I could go about this or is there something i'm missing?

**Comment by vittoriom** [comment]
Hi @unuigbee, thanks for your observation!

The question is not totally clear for me. I understand you have your own GraphQL server, and that it expects a JSON, but I don't get how the value of the `query` field in the JSON dictionary can be an invalid GraphQL query. 
AFAIK the GraphQL reference wants the query in a `{ ... }` block (or, equivalently, a `query { ... }`, or yet `query name { ... }`. Any other query would be invalid.

Is there a chance that you can pass whatever valid query to your JSON dictionary for the `query` key? In this case, you should be able to pass whatever output you get from GraphQLicious. 
If not, can you elaborate a bit more how your GraphQL server works? 

Thanks!

**Comment by unuigbee** [comment]
I was able to figure it out. I made a silly typo when making a request. A query like this in JSON is perfectly fine: { "query": "query { feed(type: BY_VOTE) { title } }" }.

**Comment by vittoriom** [comment]
All right, I'm glad it worked out eventually! All the best for your app!
