### ISSUE TITLE
Mutation - Passing in an array of Ints for Mutating Field value

### ISSUE THREAD

**Issue by thomasbaldwin** [WeltN24/GraphQLicious#15]
Here's the mutation I'm trying to accomplish:

<img width="875" alt="screen shot 2016-08-27 at 5 22 02 pm" src="https://cloud.githubusercontent.com/assets/5099084/18030178/4cb1dfde-6c7b-11e6-9a12-a367a5ddcfbd.png">

However, I'm getting an error when trying to set up my MutatingField values like so:

<img width="900" alt="screen shot 2016-08-27 at 5 23 02 pm" src="https://cloud.githubusercontent.com/assets/5099084/18030173/00abfd22-6c7b-11e6-9170-4701d7878f77.png">

Is it possible to accomplish this?

**Comment by vittoriom** [comment]
Hi @thomasbaldwin,

I have a bit of confusion about why you're setting up `targetCommitteeIds` since in the screenshot I can't see them. I assume it's supposed to be there in the request too.
At the moment, there's apparently no way to pass multiple arguments to a mutation request.

I'll speak tomorrow with @joemcbomb to see how we can approach this issue (I already have 2 ideas in mind). Theoretically it shouldn't take long before this is implemented and added to the library.

I'll get back to you here!

**Comment by vittoriom** [comment]
Hi @thomasbaldwin,

we decided which approach to follow, and you'll be able to pass multiple arguments to a mutation request soon. 

We'll post back here when the implementation is on master. Thanks for the heads up!

**Comment by thomasbaldwin** [comment]
Hey @vittoriom,

Thanks for your prompt reply, and thanks again for this awesome library! 👍

**Comment by vittoriom** [comment]
Hi @thomasbaldwin, you should be able to create the `Mutation` you wanted now.

```swift
let sampleMutation = Mutation(withAlias: "AddEvent", mutatingRequest: Request(name: "addEvent", arguments: [
      Argument(key: "title", value: "Test Event"),
      Argument(key: "targetGroupIds", values: event.targetGroups.flatMap { $0.id }),
      Argument(key: "targetCommitteeIds", values: event.targetCommittees.flatMap { $0.id })
    ], fields: [
      "title",
      Request(name: "targetGroups", fields: [
        "id"
      ])
]))
```

**Output:**
```
query AddEvent {
         addEvent (title: "Test Event", targetGroupIds: [1,2,3], targetCommitteeIds: [1,2]) {
                title,
                targetGroups{
                  id
                }
         }
}
```

**Comment by thomasbaldwin** [comment]
Thanks a lot @vittoriom ! I take it the updates aren't available via cocoapods yet?

**Comment by vittoriom** [comment]
Hi @thomasbaldwin,
Exactly, the updates are not available via cocoapods yet. We'll probably make a release in a week or so. In the mean time are you able to use master?

**Comment by thomasbaldwin** [comment]
Yeah np, thanks for the help @vittoriom !
