### ISSUE TITLE
Syntax Change

### ISSUE THREAD

**Issue by thomasbaldwin** [WeltN24/GraphQLicious#17]
Hey, I can't figure out how to do something like this with the new syntax:

```swift
mutation myMutation {
    editMe(id: 1, input: {
        name: "joe",
        age: 99
    })
    {
        name,
        age
    }
}
```

I noticed we were able to do something similar with the old syntax, but I just can't figure out how to do it with the new syntax.

Here's how I'm currently trying to do it:
<img width="809" alt="screen shot 2016-09-03 at 1 58 36 pm" src="https://cloud.githubusercontent.com/assets/5099084/18226742/8f88d49e-71de-11e6-98bc-31870d705c9f.png">

And here's the old way:

``` swift
let mutatingRequest = MutatingRequest(
      mutationName: "editMe",
      mutatingArgument:
      MutatingArgument(
        key: "input",
        mutatingValue: MutatingValue(
          withFields: [
            MutatingField(name: "name", value: "joe"),
            MutatingField(name: "age", value: 99)
          ]
        )),
      responseFields: [
        "name",
        "age"
      ]
    )
```

Thanks for the help!

**Comment by vittoriom** [comment]
Hi @thomasbaldwin,

with the new syntax you should be able to do something like this:

```swift
let mutation = Mutation(withAlias: "myMutation", mutatingRequest: Request(name: "editMe", arguments: [
        Argument(key: "id", value: 1),
        Argument(key: "input", value: ObjectValue(keyValuePairs: [
            ObjectKeyValuePair(key: "name", value: "joe".withQuotes),
            ObjectKeyValuePair(key: "age", value: 99)
        ]))
      ], fields: [
        "name",
        "age"
      ]))
```

The trick is basically the `ObjectValue` type that now replaces `MutatingValue`, and `ObjectKeyValuePair` that replaces `MutatingField`. Everything else should be the same.

The query I posted above yields the following GraphQL:

```
mutation myMutation { 
    editMe (id: 1,input: {
	name: "joe",
        age: 99
    }) {
	name,
	age
    }
}
```

I hope this helps!

**Comment by thomasbaldwin** [comment]
Thanks @vittoriom! 💯
