### ISSUE TITLE
Is it possible to pass an Array of integers as a mutating field?

### ISSUE THREAD

**Issue by unuigbee** [WeltN24/GraphQLicious#18]
I have a GraphQL schema that has a GraphQL input object type that has describes an Array of Integers as part of its fields:  

```
input addSequenceInput {
   userID: ID!
   commandSequenceTitle: String!
   commandSequenceDescription: String
   commands: [Int]
  }
```

How can I craft a GraphQL mutation query that accepts an array of integers as a mutating field: 
```
func createToDoList(someList: [Int]) -> String{

        let mutatingFieldCommands = MutatingField(name: "commands", value:someList);
       
        let mutatingRequest = MutatingRequest(
            // Name of the mutation registered at our GraphQL server
            mutationName: "createToDoList",
            // The Argument that our the mutation takes
            mutatingArgument:
            MutatingArgument(
                key: "input",
                mutatingValue: MutatingValue(
                    withFields: [
                        mutatingFieldCommands
                    ] 
                )),
            responseFields: [
                "id",
                "listitem",
            ]
        );
        
        let mutation = Mutation(
            mutatingRequest: mutatingRequest
        );
        
        print(mutation.create())
        debugPrint(mutation)
        
        return mutation.create();
    }
} 
```

**Comment by vittoriom** [comment]
Hi @unuigbee,

if you pull from `master` you'll find a new API for mutations that we adapted in response to #15 

This means that you can pass an array of integers as a mutating field with the following syntax:

```swift
let testMutation = Mutation(withAlias: "myMutation", mutatingRequest: Request(name: "addSequence", arguments: [
        Argument(key: "input", value: ObjectValue(keyValuePairs: [
          ObjectKeyValuePair(key: "userId", value: 1),
          ObjectKeyValuePair(key: "commandSequenceTitle", value: "test"),
          ObjectKeyValuePair(key: "commandSequenceDescription", value: "description"),
          ObjectKeyValuePair(key: "commands", values: [1,2,3,4,5])
        ]))
      ], fields: [
        "response"
      ]))
```

As you can see there are no `MutatingRequest` and `MutatingArgument` or `MutatingField` anymore, but we're just using normal `Request`, `Argument` and the newly introduced `ObjectValue` and `ObjectKeyValuePair` (specifically meant for mutation input parameters).

I hope this answers your question!

Happy coding
Vic

**Comment by unuigbee** [comment]
That's really awesome. When will version 0.9 be available via cocoa pods. Great work by the way.

**Comment by vittoriom** [comment]
0.9 will probably be available on CocoaPods by the end of the month, since we're trying to collect some more fixes in there. Moreover the maintainer is currently away until end of the month anyway.
