### ISSUE TITLE
Add support for Bool format

### ISSUE THREAD

**Issue by navasiloy** [WeltN24/GraphQLicious#21]
Field.swift
`extension Bool: Field {
    public var asGraphQLString: String {
        return description
    }
}`

ArgumentValue.swift
`extension Bool: ArgumentValue {
    public var asGraphQLArgument: String {
        return asGraphQLString
    }
}`

**Comment by vittoriom** [comment]
Hi @navasiloy, is this something you could approach with a PR?

**Comment by wlkntlknstvnhwkn** [comment]
I added it and will pull it into the next release
