### ISSUE TITLE
Can't import, can't use

### ISSUE THREAD

**Issue by florianmari** [WeltN24/GraphQLicious#22]
Hey,

I can't use the library when I install it. I can't import it even use it

<img width="267" alt="capture d ecran 2016-10-20 a 13 54 22" src="https://cloud.githubusercontent.com/assets/1582796/19560542/da01165e-96cc-11e6-9161-b800432c74be.png">

XCode 8.0 / iOS 10

**Comment by vittoriom** [comment]
Hi, what tag of GraphQLicious are you using and which Swift version do you have in your project?

**Comment by florianmari** [comment]
Hey,

I'm using Swift 3.0 and the last one I think

`github "WeltN24/GraphQLicious"`

Isn't compatible with 3.0? Because I saw a 2.3 branch version

**Comment by vittoriom** [comment]
I think we didn't release the Swift 3 version on Carthage yet. You could just use `github "WeltN24/GraphQLicious" "master"` instead (or specify the explicit sha of the commit rather than use "master") and it should work

**Comment by florianmari** [comment]
I got this with the master

`*** Fetching GraphQLicious
*** Checking out GraphQLicious at "f7a7e7f29ba5dee4df0e239f303047ce83ce4ce5"
*** xcodebuild output can be found in /var/folders/fj/8z8hkrc97bjb4tnhkc0yjw3h0000gn/T/carthage-xcodebuild.lfZKjH.log
*** Building scheme "GraphQLicious" in GraphQLicious.xcodeproj
xcodebuild: error: Unable to find a destination matching the provided destination specifier:
		{ platform:watchOS Simulator, id:F35F660A-85AC-4095-894A-04721EB5027C }

	Available destinations for the "GraphQLicious" scheme:
		{ platform:macOS, arch:x86_64 }
		{ platform:iOS Simulator, id:2CC6CAB4-6688-41AC-83BA-8B6E8512D9DB, OS:10.0, name:iPad Air }
		{ platform:iOS Simulator, id:38FC3AEC-2868-4073-AC0F-F000588560DA, OS:10.0, name:iPad Air 2 }
		{ platform:iOS Simulator, id:535A9CFE-CA63-42D0-BEBC-C2C9D43C2749, OS:10.0, name:iPad Pro (9.7 inch) }
		{ platform:iOS Simulator, id:7F8819CE-3778-463D-B63B-8DD261159457, OS:10.0, name:iPad Pro (12.9 inch) }
		{ platform:iOS Simulator, id:3C618A54-567E-4C30-9C66-3B4C510B2E77, OS:10.0, name:iPad Retina }
		{ platform:iOS Simulator, id:C21D4489-1B70-4B09-A942-1F95A3DFBBA7, OS:10.0, name:iPhone 5 }
		{ platform:iOS Simulator, id:F218805B-714D-4DBF-B0A2-186032B5DFCC, OS:10.0, name:iPhone 5s }
		{ platform:iOS Simulator, id:5753329F-6591-4A22-B9AD-3C95FDC78146, OS:10.0, name:iPhone 6 }
		{ platform:iOS Simulator, id:196FCFE7-17EF-49BA-B8FD-88ED3BA82222, OS:10.0, name:iPhone 6 Plus }
		{ platform:iOS Simulator, id:C3F02FB2-D971-46EA-B56C-B7DA49D6E77D, OS:10.0, name:iPhone 6s }
		{ platform:iOS Simulator, id:94B6B989-AD4C-4EBF-A331-11A565375137, OS:10.0, name:iPhone 6s Plus }
		{ platform:iOS Simulator, id:E6A96AD2-07B1-420B-8BF4-D13CE1303C2B, OS:10.0, name:iPhone 7 }
		{ platform:iOS Simulator, id:ABB147FA-0121-4320-A532-22C20E938B15, OS:10.0, name:iPhone 7 Plus }
		{ platform:iOS Simulator, id:A0E85A68-9178-4E99-BBDC-83E9861B6CC2, OS:10.0, name:iPhone SE }

	Ineligible destinations for the "GraphQLicious" scheme:
		{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Generic iOS Device }
		{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Generic iOS Simulator Device }
		{ platform:tvOS, id:dvtdevice-DVTiOSDevicePlaceholder-appletvos:placeholder, name:Generic tvOS Device }
		{ platform:tvOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-appletvsimulator:placeholder, name:Generic tvOS Simulator Device }
		{ platform:watchOS, id:dvtdevice-DVTiOSDevicePlaceholder-watchos:placeholder, name:Generic watchOS Device }
		{ platform:watchOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-watchsimulator:placeholder, name:Generic watchOS Simulator Device }
A shell task (/usr/bin/xcrun xcodebuild -project /Users/florianmari/Desktop/Test/Carthage/Checkouts/GraphQLicious/GraphQLicious.xcodeproj -scheme GraphQLicious -configuration Release -sdk watchsimulator -destination "platform=watchOS Simulator,id=F35F660A-85AC-4095-894A-04721EB5027C" -destination-timeout 3 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 70:
xcodebuild: error: Unable to find a destination matching the provided destination specifier:
		{ platform:watchOS Simulator, id:F35F660A-85AC-4095-894A-04721EB5027C }

	Available destinations for the "GraphQLicious" scheme:
		{ platform:macOS, arch:x86_64 }
		{ platform:iOS Simulator, id:2CC6CAB4-6688-41AC-83BA-8B6E8512D9DB, OS:10.0, name:iPad Air }
		{ platform:iOS Simulator, id:38FC3AEC-2868-4073-AC0F-F000588560DA, OS:10.0, name:iPad Air 2 }
		{ platform:iOS Simulator, id:535A9CFE-CA63-42D0-BEBC-C2C9D43C2749, OS:10.0, name:iPad Pro (9.7 inch) }
		{ platform:iOS Simulator, id:7F8819CE-3778-463D-B63B-8DD261159457, OS:10.0, name:iPad Pro (12.9 inch) }
		{ platform:iOS Simulator, id:3C618A54-567E-4C30-9C66-3B4C510B2E77, OS:10.0, name:iPad Retina }
		{ platform:iOS Simulator, id:C21D4489-1B70-4B09-A942-1F95A3DFBBA7, OS:10.0, name:iPhone 5 }
		{ platform:iOS Simulator, id:F218805B-714D-4DBF-B0A2-186032B5DFCC, OS:10.0, name:iPhone 5s }
		{ platform:iOS Simulator, id:5753329F-6591-4A22-B9AD-3C95FDC78146, OS:10.0, name:iPhone 6 }
		{ platform:iOS Simulator, id:196FCFE7-17EF-49BA-B8FD-88ED3BA82222, OS:10.0, name:iPhone 6 Plus }
		{ platform:iOS Simulator, id:C3F02FB2-D971-46EA-B56C-B7DA49D6E77D, OS:10.0, name:iPhone 6s }
		{ platform:iOS Simulator, id:94B6B989-AD4C-4EBF-A331-11A565375137, OS:10.0, name:iPhone 6s Plus }
		{ platform:iOS Simulator, id:E6A96AD2-07B1-420B-8BF4-D13CE1303C2B, OS:10.0, name:iPhone 7 }
		{ platform:iOS Simulator, id:ABB147FA-0121-4320-A532-22C20E938B15, OS:10.0, name:iPhone 7 Plus }
		{ platform:iOS Simulator, id:A0E85A68-9178-4E99-BBDC-83E9861B6CC2, OS:10.0, name:iPhone SE }

	Ineligible destinations for the "GraphQLicious" scheme:
		{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Generic iOS Device }
		{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Generic iOS Simulator Device }
		{ platform:tvOS, id:dvtdevice-DVTiOSDevicePlaceholder-appletvos:placeholder, name:Generic tvOS Device }
		{ platform:tvOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-appletvsimulator:placeholder, name:Generic tvOS Simulator Device }
		{ platform:watchOS, id:dvtdevice-DVTiOSDevicePlaceholder-watchos:placeholder, name:Generic watchOS Device }
		{ platform:watchOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-watchsimulator:placeholder, name:Generic watchOS Simulator Device }`

If I use pod "GraphQLicious" I can't import GraphQLicious as well should it be released on Swift 3.0 via Pods?

**Comment by vittoriom** [comment]
Maybe it's because you're using it on a WatchOS scheme. We don't support WatchOS with GraphQLicious at the moment.

**Comment by florianmari** [comment]
Yeah it works! That's perfect thank you! Have a good day
