### ISSUE TITLE
Carthage build not working because Sample is requiring provisioning profile

### ISSUE THREAD

**Issue by gautier-gdx** [WeltN24/GraphQLicious#23]
I got this when trying to build with carthage

`** BUILD FAILED **

The following build commands failed:
	Check dependencies
(1 failure)
A shell task failed with exit code 65:
** BUILD FAILED **`

I forked your Repo, removed sample in my fork and used Carthage on it and it worked, so the missing provisioning profile is the key,

PS: I'll will soon use your lib in our app [Swapcard](https://itunes.apple.com/app/swapcard-carte-visite-numerique/id879488719?mt=8), that's a really cool lib, would be happy to contribute if I find something useful :)

**Comment by vittoriom** [comment]
Hi @gautier-gdx, thanks for bringing this up! 

That's super nice that you're using GraphQLicious in your app. We can make you a contributor if you're planning to add more features to it!

Regarding this issue, what is your suggested solution?

**Comment by gautier-gdx** [comment]
In my opinion you should not put your example as a target in your framework but make a standalone project who will be using graphQLicious (with carthage Cocoapod or as a submodule), and do not put it in the root folder but in an other folder, check my lib Hexacon[https://github.com/gautier-gdx/Hexacon/tree/swift-3.0](url) for a quick example, with this methods Carthage will not try to build the example

**Comment by wlkntlknstvnhwkn** [comment]
Hi @gautier-gdx,
a thank you from my side as well :)
I'll take care of it tomorrow.
Cheers

**Comment by wlkntlknstvnhwkn** [comment]
Done
