### ISSUE TITLE
cocoapods seems out of date

### ISSUE THREAD

**Issue by zachschultz** [WeltN24/GraphQLicious#24]
Installing through cocoapods and trying to build brings forth a slew of errors, like 'SequenceType' has been renamed to 'Sequence', and 'Use of undeclared type 'Generator''

**Comment by wlkntlknstvnhwkn** [comment]
Hi Zach.
I'll have a look at it today :)

**Comment by wlkntlknstvnhwkn** [comment]
@zachschultz Cocoapods should be up to date now :)

Cheers
