### ISSUE TITLE
its not full

### ISSUE THREAD

**Issue by saroar** [WeltN24/GraphQLicious#25]
please can you add full guide line please 

like 
1. add server side link login
2. registration by mutations

Apollo 
let apollo = ApolloClient(url: URL(string: "http://localhost:3000/api")!)

**Comment by wlkntlknstvnhwkn** [comment]
Hi @saroar, thank you for your feedback :)

I hope I am getting what you mean:
As far as I am concerned the way you register or log into your graphQL backend is based on the specific implementation of that backend. GraphQLicious is meant to be a very generic tool to create graphQL queries.

The specific mutation arguments your API accepts for a registration for example might not be the same for another API. This information is something you have to provide in your business logic.
