### ISSUE TITLE
Add support for mutations

### ISSUE THREAD

**Issue by vittoriom** [WeltN24/GraphQLicious#9]
https://facebook.github.io/relay/graphql/mutations.htm

**Comment by kevinfez** [comment]
Part of mutations is being able to nest arguments in arrays and dictionaries;
An example mutation would be:
```
mutation {
  doSomething(input:{
    userId: "userId"
    otherId: "otherId"
    actions:[{
      action:someActionEnum
      date: 1462991657100
    }, {
      action:someActionEnum
      date: 1462991711537
    }]
  }) {
    response {
      ...Fragment
    }
  }
}
```
Is the nested array and dictionary Argument functionality already supported in the project?

**Comment by joemcbomb** [comment]
I have some free time tonight. Let me see what I can come up with :P
